# Generated by Django 3.1.14 on 2023-09-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20230904_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(null=True, verbose_name='Disappeared at:'),
        ),
    ]
